PermitRootLogin no
PubkeyAuthentication yes
AuthenticationMethods publickey
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitEmptyPasswords no
AllowUsers hieunt
LogLevel VERBOSE
MaxAuthTries 3
LoginGraceTime 30
